'use client';

import { useMemo } from 'react';

/**
 * Builds the four Downloads context provider values (memoized).
 */
export function useDownloadsProviderValues({
  apiKey,
  filterData,
  tags,
  activeType,
  handleColumnChange,
  viewItems,
  sortedItems,
  visibleIds,
  activeColumns,
  downloadHistoryLookup,
  tagMappings,
  protectedMap,
  isBackendAvailable,
  isBlurred,
  setIsBlurred,
  isFullscreen,
  onFullscreenToggle,
  displayViewMode,
  setViewMode,
  isDownloadPanelOpen,
  setIsDownloadPanelOpen,
  scrollContainerRef,
  filtersSidebarExpanded,
  expandAllFiles,
  collapseAllFiles,
  isDownloading,
  handleBulkDownload,
  isDeleting,
  deleteItems,
  isArchiving,
  archiveItems,
  isExporting,
  handleBulkExport,
  getTotalDownloadSize,
  setToast,
  handleFileSelect,
  setSelectedItems,
  handleSelectAll,
  deleteItem,
  archiveItem,
  stopSeedingItem,
  stopSeedingItems,
  isStoppingSeeding,
  protectItems,
  unprotectItems,
  toggleProtectionForItem,
  isUpdatingProtection,
  toggleFiles,
  openVideoPlayer,
  handleAudioPlay,
}) {
  const sidebarProps = useMemo(
    () => ({
      apiKey,
      views: filterData.views,
      activeView: filterData.activeView,
      activeViewIds: filterData.activeViewIds,
      tags,
      activeAssetType: activeType,
      activeTagIds: filterData.activeTagIds,
      activeTrackers: filterData.activeTrackers,
      activeSources: filterData.activeSources,
      onApplyView: filterData.handleApplyView,
      onApplyViewRange: filterData.handleApplyViewRange,
      onClearViews: filterData.handleClearViews,
      onClearView: filterData.handleClearFilters,
      onApplyTag: filterData.handleApplyTag,
      onApplyTagRange: filterData.handleApplyTagRange,
      onClearTags: filterData.handleClearTags,
      onApplyTracker: filterData.handleApplyTracker,
      onApplyTrackerRange: filterData.handleApplyTrackerRange,
      onClearTrackers: filterData.handleClearTrackers,
      onApplySource: filterData.handleApplySource,
      onApplySourceRange: filterData.handleApplySourceRange,
      onClearSources: filterData.handleClearSources,
      onEditView: filterData.handleEditView,
      onRenameView: filterData.handleRenameView,
      onRenameTag: filterData.handleRenameTag,
      onDeleteTag: filterData.handleTagDeleted,
      onNewFilter: filterData.handleOpenNewFilter,
      onNewView: filterData.handleOpenNewView,
      onOpenTagManager: filterData.handleOpenTagManager,
    }),
    [
      apiKey,
      filterData.views,
      filterData.activeView,
      filterData.activeViewIds,
      tags,
      activeType,
      filterData.activeTagIds,
      filterData.activeTrackers,
      filterData.activeSources,
      filterData.handleApplyView,
      filterData.handleApplyViewRange,
      filterData.handleClearViews,
      filterData.handleClearFilters,
      filterData.handleApplyTag,
      filterData.handleApplyTagRange,
      filterData.handleClearTags,
      filterData.handleApplyTracker,
      filterData.handleApplyTrackerRange,
      filterData.handleClearTrackers,
      filterData.handleApplySource,
      filterData.handleApplySourceRange,
      filterData.handleClearSources,
      filterData.handleEditView,
      filterData.handleRenameView,
      filterData.handleRenameTag,
      filterData.handleTagDeleted,
      filterData.handleOpenNewFilter,
      filterData.handleOpenNewView,
      filterData.handleOpenTagManager,
    ]
  );

  const downloadsDataContextValue = useMemo(
    () => ({
      viewItems,
      sortedItems,
      visibleIds,
      activeColumns,
      downloadHistoryLookup,
      tagMappings,
      protectedMap,
    }),
    [
      viewItems,
      sortedItems,
      visibleIds,
      activeColumns,
      downloadHistoryLookup,
      tagMappings,
      protectedMap,
    ]
  );

  const downloadsFilterContextValue = useMemo(
    () => ({
      appliedFilters: filterData.appliedFilters,
      activeView: filterData.activeView,
      activeViewIds: filterData.activeViewIds,
      tags,
      handleClearFilters: filterData.handleClearFilters,
      handleOpenNewFilter: filterData.handleOpenNewFilter,
      handleEditActiveFilters: filterData.handleEditActiveFilters,
      handleColumnChange,
      search: filterData.search,
      debouncedSearch: filterData.debouncedSearch,
      setSearch: filterData.setSearch,
      statusFilter: filterData.statusFilter,
      setStatusFilter: filterData.setStatusFilter,
      sortField: filterData.sortField,
      sortDirection: filterData.sortDirection,
      handleSort: filterData.handleSort,
    }),
    [
      filterData.appliedFilters,
      filterData.activeView,
      filterData.activeViewIds,
      tags,
      filterData.handleClearFilters,
      filterData.handleOpenNewFilter,
      filterData.handleEditActiveFilters,
      handleColumnChange,
      filterData.search,
      filterData.debouncedSearch,
      filterData.setSearch,
      filterData.statusFilter,
      filterData.setStatusFilter,
      filterData.sortField,
      filterData.sortDirection,
      filterData.handleSort,
    ]
  );

  const downloadsUIContextValue = useMemo(
    () => ({
      isBackendAvailable,
      activeType,
      isBlurred,
      setIsBlurred,
      isFullscreen,
      onFullscreenToggle,
      displayViewMode,
      setViewMode,
      isDownloadPanelOpen,
      setIsDownloadPanelOpen,
      scrollContainerRef,
      filtersSidebarExpanded,
      expandAllFiles,
      collapseAllFiles,
    }),
    [
      isBackendAvailable,
      activeType,
      isBlurred,
      setIsBlurred,
      isFullscreen,
      onFullscreenToggle,
      displayViewMode,
      setViewMode,
      isDownloadPanelOpen,
      setIsDownloadPanelOpen,
      scrollContainerRef,
      filtersSidebarExpanded,
      expandAllFiles,
      collapseAllFiles,
    ]
  );

  const downloadsContextValue = useMemo(
    () => ({
      isDownloading,
      handleBulkDownload,
      isDeleting,
      deleteItems,
      isArchiving,
      archiveItems,
      isExporting,
      handleBulkExport,
      getTotalDownloadSize,
      apiKey,
      setToast,
      handleFileSelect,
      setSelectedItems,
      handleSelectAll,
      deleteItem,
      archiveItem,
      stopSeedingItem,
      stopSeedingItems,
      isStoppingSeeding,
      protectItems,
      unprotectItems,
      toggleProtectionForItem,
      isUpdatingProtection,
      toggleFiles,
      onOpenVideoPlayer: openVideoPlayer,
      onAudioPlay: handleAudioPlay,
    }),
    [
      isDownloading,
      handleBulkDownload,
      isDeleting,
      deleteItems,
      isArchiving,
      archiveItems,
      isExporting,
      handleBulkExport,
      getTotalDownloadSize,
      apiKey,
      setToast,
      handleFileSelect,
      setSelectedItems,
      handleSelectAll,
      deleteItem,
      archiveItem,
      stopSeedingItem,
      stopSeedingItems,
      isStoppingSeeding,
      protectItems,
      unprotectItems,
      toggleProtectionForItem,
      isUpdatingProtection,
      toggleFiles,
      openVideoPlayer,
      handleAudioPlay,
    ]
  );

  return {
    sidebarProps,
    downloadsDataContextValue,
    downloadsFilterContextValue,
    downloadsUIContextValue,
    downloadsContextValue,
  };
}
