'use client';

import { useMemo } from 'react';

/**
 * Builds the four Downloads context provider values (memoized).
 */
export function useDownloadsProviderValues({
  apiKey,
  filterData,
  tags,
  activeType,
  handleColumnChange,
  viewItems,
  sortedItems,
  visibleIds,
  activeColumns,
  downloadHistoryLookup,
  tagMappings,
  isBackendAvailable,
  isBlurred,
  setIsBlurred,
  isFullscreen,
  onFullscreenToggle,
  displayViewMode,
  setViewMode,
  isDownloadPanelOpen,
  setIsDownloadPanelOpen,
  scrollContainerRef,
  filtersSidebarExpanded,
  expandAllFiles,
  collapseAllFiles,
  isDownloading,
  handleBulkDownload,
  isDeleting,
  deleteItems,
  isExporting,
  handleBulkExport,
  getTotalDownloadSize,
  setToast,
  handleFileSelect,
  setSelectedItems,
  handleSelectAll,
  deleteItem,
  toggleFiles,
  openVideoPlayer,
  handleAudioPlay,
}) {
  const sidebarProps = useMemo(
    () => ({
      apiKey,
      views: filterData.views,
      activeView: filterData.activeView,
      tags,
      activeAssetType: activeType,
      activeTagIds: filterData.activeTagIds,
      onApplyView: filterData.handleApplyView,
      onClearView: filterData.handleClearFilters,
      onApplyTag: filterData.handleApplyTag,
      onEditView: filterData.handleEditView,
      onRenameView: filterData.handleRenameView,
      onRenameTag: filterData.handleRenameTag,
      onDeleteTag: filterData.handleTagDeleted,
      onNewFilter: filterData.handleOpenNewFilter,
      onNewView: filterData.handleOpenNewView,
      onOpenTagManager: filterData.handleOpenTagManager,
    }),
    [
      apiKey,
      filterData.views,
      filterData.activeView,
      tags,
      activeType,
      filterData.activeTagIds,
      filterData.handleApplyView,
      filterData.handleClearFilters,
      filterData.handleApplyTag,
      filterData.handleEditView,
      filterData.handleRenameView,
      filterData.handleRenameTag,
      filterData.handleTagDeleted,
      filterData.handleOpenNewFilter,
      filterData.handleOpenNewView,
      filterData.handleOpenTagManager,
    ]
  );

  const downloadsDataContextValue = useMemo(
    () => ({
      viewItems,
      sortedItems,
      visibleIds,
      activeColumns,
      downloadHistoryLookup,
      tagMappings,
    }),
    [viewItems, sortedItems, visibleIds, activeColumns, downloadHistoryLookup, tagMappings]
  );

  const downloadsFilterContextValue = useMemo(
    () => ({
      appliedFilters: filterData.appliedFilters,
      activeView: filterData.activeView,
      tags,
      handleClearFilters: filterData.handleClearFilters,
      handleOpenNewFilter: filterData.handleOpenNewFilter,
      handleEditActiveFilters: filterData.handleEditActiveFilters,
      handleColumnChange,
      search: filterData.search,
      setSearch: filterData.setSearch,
      statusFilter: filterData.statusFilter,
      setStatusFilter: filterData.setStatusFilter,
      sortField: filterData.sortField,
      sortDirection: filterData.sortDirection,
      handleSort: filterData.handleSort,
    }),
    [
      filterData.appliedFilters,
      filterData.activeView,
      tags,
      filterData.handleClearFilters,
      filterData.handleOpenNewFilter,
      filterData.handleEditActiveFilters,
      handleColumnChange,
      filterData.search,
      filterData.setSearch,
      filterData.statusFilter,
      filterData.setStatusFilter,
      filterData.sortField,
      filterData.sortDirection,
      filterData.handleSort,
    ]
  );

  const downloadsUIContextValue = useMemo(
    () => ({
      isBackendAvailable,
      activeType,
      isBlurred,
      setIsBlurred,
      isFullscreen,
      onFullscreenToggle,
      displayViewMode,
      setViewMode,
      isDownloadPanelOpen,
      setIsDownloadPanelOpen,
      scrollContainerRef,
      filtersSidebarExpanded,
      expandAllFiles,
      collapseAllFiles,
    }),
    [
      isBackendAvailable,
      activeType,
      isBlurred,
      setIsBlurred,
      isFullscreen,
      onFullscreenToggle,
      displayViewMode,
      setViewMode,
      isDownloadPanelOpen,
      setIsDownloadPanelOpen,
      scrollContainerRef,
      filtersSidebarExpanded,
      expandAllFiles,
      collapseAllFiles,
    ]
  );

  const downloadsContextValue = useMemo(
    () => ({
      isDownloading,
      handleBulkDownload,
      isDeleting,
      deleteItems,
      isExporting,
      handleBulkExport,
      getTotalDownloadSize,
      apiKey,
      setToast,
      handleFileSelect,
      setSelectedItems,
      handleSelectAll,
      deleteItem,
      toggleFiles,
      onOpenVideoPlayer: openVideoPlayer,
      onAudioPlay: handleAudioPlay,
    }),
    [
      isDownloading,
      handleBulkDownload,
      isDeleting,
      deleteItems,
      isExporting,
      handleBulkExport,
      getTotalDownloadSize,
      apiKey,
      setToast,
      handleFileSelect,
      setSelectedItems,
      handleSelectAll,
      deleteItem,
      toggleFiles,
      openVideoPlayer,
      handleAudioPlay,
    ]
  );

  return {
    sidebarProps,
    downloadsDataContextValue,
    downloadsFilterContextValue,
    downloadsUIContextValue,
    downloadsContextValue,
  };
}
